### PR TITLE
Logger migration to slf4j for all simulap components : SIP

### LINKED ISSUE #13: Logger migration to slf4j for all simulap components : SIP
## Description
Logger migration to slf4j for all simulap components : SIP

## Motivation and Context

* Project context: 
* SIMULAP version: 
* Operating System version: 

## Checklist

- [x] I have updated the documentation accordingly.
- [x] I give my issue a label.
- [ ] I put my issue into `Support` project.
- [ ] I provide the required resources.

### PR DESCRIPTION
**Pull request by hemanth-vulavala**
## Description
Logger migration to slf4j for all simulap components : SIP
see ALM ID :33846 Logger migration to slf4j for all simulap components : SIP

Fixes #13.

## Changes proposed in this pull request

- migration to SLF4J 
- SLF4J recommendation are incorporated  
- code review changes are incorporated 

## Checklist:

- [x] I have updated the documentation accordingly.
- [x] I give my PR a label.
- [x] I provide the required resources.

### CODE REVIEW

**Comment by hemanth-vulavala** [comment]
ALM ID :33846
Logger migration to slf4j for all simulap components : SIP
Issue : Logger migration to slf4j for all simulap components : SIP #14 code review releated cahnges

**Comment by vherilier** [comment]
PR refused because duplicate of #13

**Comment by vherilier** [comment]
Because of losing previous branch for PR #14, current one is being re-opened

**Comment by vherilier** [comment]
> ALM ID :33846
> Logger migration to slf4j for all simulap components : SIP
> Issue : Logger migration to slf4j for all simulap components : SIP #14 code review releated cahnges

Please @hemanth-vulavala, could you add this information into the PR description, not in the discussion?

**Pull request merged**
